; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin_s2_mini

[env]
platform = espressif32
board = lolin_s2_mini
framework = arduino
lib_deps =
	rans=symlink://../pio-library/lib/Config
	contrem/arduino-timer@^3.0.0
build_flags =
	-D WIFI_TIMEOUT=15000
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	time

[env:lolin_s2_mini]
upload_speed = 921600

[env:wemos_d1_mini32]
board = wemos_d1_mini32

[env:esp32-s2-saola-1]
board = esp32-s2-saola-1

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D PIN_LED=8