; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin_s2_mini

[env]
platform = espressif32
framework = arduino
lib_deps = 
	rans=symlink://../pio-library/lib/Config
	contrem/arduino-timer@^3.0.0
	fastled/FastLED@^3.10.3
build_flags = 
	-D WIFI_TIMEOUT=15000
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	time

[env:lolin_s2_mini]
board = lolin_s2_mini

[env:wemos_d1_mini32]
board = wemos_d1_mini32

;Olimex ESP32-S2
[env:esp32-s2-saola-1]
board = esp32-s2-saola-1

;ESP32-C3-MICRO
[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D PIN_LED=8

;ESP32-S3-UNO D1 R3 whatever kinai
[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
board_build.partitions = default_16MB.csv
build_flags = 
	-D BOARD_S3
	-D RGB_LED